### ISSUE TITLE
Tree Segmentation fails with numpy/deepforest dependency errors on macOS

### ISSUE THREAD

**Issue by Hayjay1995** [opengeos/geoai#891]
ERROR 1:
ImportError: cannot import name 'functional' from 'albumentations'

ERROR 2:
Failed to load model: module 'numpy' has no attribute 'long'

**Comment by ichisa** [comment]
I am getting same error while working on Ubuntu 24.04.4 LTS Budgie Version 10.9.1 and QGIS 3.44. 

<img width="998" height="587" alt="Image" src="https://github.com/user-attachments/assets/ecd43bc0-2526-4afc-b7fe-f8e7a3ee5d35" />

I can still open the plugin but when trying to use DeepForest I cannot load the model:

<img width="1002" height="591" alt="Image" src="https://github.com/user-attachments/assets/e4910477-f69f-4163-b9e0-8827e34d53bc" />

Plus when I try deactivating and activating the plugin I get following error and cannot load Plugin anymore

```
Couldn't load plugin 'geoai' due to an error when calling its classFactory() method 

AttributeError: module 'geoai' has no attribute 'classFactory' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 478, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.qgis_geoai/venv_py3.12/lib/python3.12/site-packages/geoai/__init__.py", line 556, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'geoai' has no attribute 'classFactory'

Python version: 3.12.3 (main, Jun 19 2026, 12:46:00) [GCC 13.3.0] 
QGIS version: 3.44.7-Solothurn Solothurn, ea262bc5ed8 
```

**Comment by HarshShinde0** [comment]
This is a follow-up to #906, closing in favor of that issue.
